### ISSUE TITLE
兄弟的库很赞，有没有可能live reload？？

### ISSUE THREAD

**Issue by hydyy** [molon/MLLayout#18]
如果可以的话，就太赞了！

**Comment by molon** [comment]
@hydyy live reload是个啥，这个库坦白说文档不全，能碰到一个愿意用的人不容易啊，哈哈。

**Comment by hydyy** [comment]
想用reactnative 但是普及到团队成本有点高。 但是喜欢flex布局啊，就找到你这了。

完善下吧，还是很棒的。

实时预览啊~ 拆出来一个布局文件，模拟器监控刷新。

**Comment by molon** [comment]
@hydyy 主要是没什么时间去整啦。
已有功能我在上个项目里用了蛮久了，现在还是蛮稳定的，使用过程中发现了什么BUG请及时反馈哈。 :)
